//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RationShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSDB
    {
        public int RationNo { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> Age { get; set; }
        public string ContactNo { get; set; }
        public string Status { get; set; }
        public string Role { get; set; }
    }
}
